### ISSUE TITLE
Tokens being regenerated under certain conditions

### ISSUE THREAD

**Issue by KcYoung1997** [coccyx/gogen#36]
When all of the tokens have been used in the 'lines' then any further use of the tokens will cause the tokens value to be generated again.

In the example config below, an example output would be:
`3,2,3,4,1,1,4,2`

After uncommenting the `- name: BUG_FIXER` line, an example output would be:
`5,5,5,5,5,5,5,5`

I'm assuming that this output is closer to what the output should look like.

Example Config:
```
samples:
  - name: bug
    interval: 1
    earliest: -1s
    endIntervals: 1
    count: 1

    tokens:
      - name: host
        format: template
        type: choice
        choice:
        - 1
        - 2
        - 3
        - 4
        - 5
      - name: BUG_FIXER
    lines:
      - _raw: "$host$,$host$,$host$,$host$,$host$,$host$,$host$,$host$"
```
